/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import com.borhan.bdpfl.dummy.testcase1;
	
	import flash.display.Sprite;
	import com.borhan.bdpfl.dummy.testcase2;
	import com.borhan.bdpfl.DummySuit;
	
	public class FlexUnitCompilerApplication extends Sprite {
		private var com_borhan_bdpfl_DummySuit_obj:com.borhan.bdpfl.DummySuit;
		private var com_borhan_bdpfl_dummy_testcase2_obj:com.borhan.bdpfl.dummy.testcase2;
		
		
		private var com_borhan_bdpfl_testcase1_obj:com.borhan.bdpfl.dummy.testcase1;
	}
}